version: '3.2'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    # [인증서 파일 저장 경로]:/var/www/html
    volumes:
      - /home/ubuntu/docker-volume/ssl:/var/www/html
    container_name: "frontend"
    networks:
      - isf6

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      # [인증서 파일 저장 경로]:/root
    volumes:
      - /home/ubuntu/docker-volume:/root
    container_name: "backend"
    networks:
      - isf6

  # db:
  #   image: mysql
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 0000
  #     MYSQL_DATABASE: zumgo	// database 이름
  #     MYSQL_USER: isf6
  #     MYSQL_PASSWORD: isf6
  #     TZ: Asia/Seoul
  #   volumes:
  #     - ./db/mysql/data:/var/lib/mysql
  #     - ./db/mysql/config:/etc/mysql/conf.d
  #     - ./db/mysql/init:/docker-entrypoint-initdb.d

networks:
  isf6:
